# Generated by Django 2.2 on 2022-05-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermodel',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='bannermodel',
            old_name='display_order',
            new_name='orders',
        ),
        migrations.RenameField(
            model_name='bannermodel',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
